apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= 
  mysql-user: d29yZHByZXNz  
  mysql-password: d29yZHByZXNz  
